SAP/cloud-security-services-integration-library

.gitignore, spring-xsuaa/src/main/java/com/sap/xs2/security/container/UserInfo.java, spring-xsuaa/src/main/java/com/sap/xs2/security/container/UserInfoAuthenticationConverter.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTest.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTestClientCredentials.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTestEndUser.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTestSAML.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTestUser.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTestUtil.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/XSTokenRequestImplTest.java, spring-xsuaa/src/test/resources/claims_template.txt
@mwdb 
Question: is it possible, that the JWT claim "origin" is not filled? Because in the `UserInfoTestEndUser` test the jwt token had no "origin" claim.
This PR fixes the issue https://github.com/SAP/cloud-security-xsuaa-integration/issues/9
=> UserInfo is set as Principle but does not satisfy Spring Spec

spring-xsuaa/README.md
=> xsuaa README.md explain how to check authorizations within a method

CHANGELOG.md, api/pom.xml, pom.xml, samples/sap-java-buildpack-api-usage/pom.xml, samples/spring-security-basic-auth/pom.xml, samples/spring-security-xsuaa-usage/pom.xml, spring-xsuaa-it/pom.xml, spring-xsuaa-mock/pom.xml, spring-xsuaa-test/pom.xml, spring-xsuaa/pom.xml, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidator.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidatorTest.java, spring-xsuaa/src/test/resources/audience_3.txt, spring-xsuaa/src/test/resources/audience_4.txt
* Broker plan validation failed due to incorrect audience validation
=> Broker fix

spring-xsuaa-mock/README.md
Add imports to copy/paste sample
=> Add imports

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/Token.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/TokenImpl.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/TokenImplTest.java
closes #https://github.com/SAP/cloud-security-xsuaa-integration/issues/68
=> new method: Token.getExpirationDate()

troubleshooting/logcollector/README.md
I fixed the links pointing to the raw files to make it possible to download them.
=> Error fixing

troubleshooting/README.md
Readme file added as discussed with Mathias.
=> Add Troubleshooting section to Readme

.travis.yml
With this commit all Tests are executed:
[INFO] parent  ....................................... SUCCESS [  0.154 s]
[INFO] api ................................................ SUCCESS [  4.569 s]
[INFO] spring-xsuaa-test .................................. SUCCESS [ 13.677 s]
[INFO] spring-xsuaa ....................................... SUCCESS [ 21.584 s]
[INFO] spring-xsuaa-mock .................................. SUCCESS [ 17.159 s]
[INFO] spring-xsuaa-it  .............................. SUCCESS [ 19.170 s]
=> execute also tests spring-xsuaa-it directory

spring-xsuaa/README.md
In order that auto-configuration works it must be of type XsuaaServiceConfiguration
=> Fix README

troubleshooting/logcollector/README.md
Small changes and additions to the documentation of the logcollector as discussed with @nedo-SAP
=> Additional Documentation for the logcollector

troubleshooting/logcollector/README.md, troubleshooting/logcollector/cf-logcollector.sh
Small changes in documentation and formatting, as discussed with @nedo-SAP
=> Documentation changes

spring-xsuaa-test/src/main/java/com/sap/cloud/security/xsuaa/test/JwtGenerator.java, spring-xsuaa-test/src/test/java/com/sap/cloud/security/xsuaa/test/JwtGeneratorTest.java
* Make Header extensible
* Make createFromClaims accessible
* Introduce TokenHeaders class (similarly to TokenClaims)
=> Better configurability for JwtGenerator

samples/spring-security-basic-auth/README.md, samples/spring-security-basic-auth/pom.xml, samples/spring-security-basic-auth/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java, samples/spring-security-basic-auth/src/main/java/sample/spring/xsuaa/TestController.java, samples/spring-security-basic-auth/src/main/resources/application.yml, samples/spring-security-xsuaa-usage/README.md, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/TokenBrokerResolver.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/UaaTokenBroker.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/ReactiveSecurityContext.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/Assertions.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenService.java
=> Improve Caching of basic authentication sample

token-client/README.md, token-client/pom.xml, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenService.java
Added new implementation of AbstractOAuth2TokenService that uses the Apache HttpClient.
=> Apache HTTPClient support

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java
Error behaviour should now match the spring http client version.
=> Added response body to exception message when error occurred

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenServiceTest.java
Test for DefaultOAuth2TokenService plus new Exception when expires_in is missing.
=> Test for DefaultOAuth2TokenService

pom.xml, spring-xsuaa-mock/pom.xml, spring-xsuaa-test/pom.xml, spring-xsuaa/pom.xml, token-client/pom.xml
This is a fix for #142 
I also updated the version that was currently to the newest stable version.
=> Added version specifier to maven-source-plugin

token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/PasswordTokenFlow.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/XsuaaTokenFlows.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/ClientCredentialsTokenFlowTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/PasswordTokenFlowTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/RefreshTokenFlowTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/TestConstants.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/UserTokenFlowTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/XsuaaTokenFlowsTest.java
This is the implementation of the password token flow with tests.
I also added some test constants and made the naming more consistent therefore some older tests were touched as well.
=> Password token flow and tests

pom.xml, samples/java-tokenclient-usage/pom.xml, samples/spring-security-basic-auth/pom.xml, samples/spring-security-xsuaa-usage/pom.xml, samples/spring-webflux-security-xsuaa-usage/pom.xml, spring-xsuaa-it/pom.xml, spring-xsuaa-mock/pom.xml, spring-xsuaa-starter/pom.xml, spring-xsuaa-test/pom.xml, spring-xsuaa/pom.xml, token-client/pom.xml
In this pull request I have moved the maven dependency declarations to the parent pom.xml file using dependency management. Now it is possible to omit the version definition in the sub modules and therefore all sub modules will use the same version of the respective dependency.
I hope this solves issue #43.
=> Version convergence

spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/SpringSecurityContextTest.java
Sporadically the `setSecurityContext` test from the `SpringSecurityContextTest` class does not finish executing. This leads to non deterministic test failures. My assumption is that the thread occasionally dead locked on the waiting logic.
I wonder why this logic was implemented in the first place since the `get` on line [84/85](https://github.com/SAP/cloud-security-xsuaa-integration/compare/ConcurrencyProblemInTest?expand=1#diff-5dbd7adf9ddfc3a91532892d4196b4f6L84) already blocks the threads until the execution is finished.
Maybe I did not understand the test and my changes made it useless..😃 In this case the concurrency bug should also be solvable without remove the waiting logic. I would create another pull request for that.
Thank you!
=> Removed waiting logic from test

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaResourceServerJwkAutoConfiguration.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoderBuilder.java
Made it possible to replace RestOperations in JwtDecoder via Builder.
=> Custom RestOperations in JwtDecoder

samples/spring-security-basic-auth/pom.xml, samples/spring-security-xsuaa-usage/pom.xml, samples/spring-webflux-security-xsuaa-usage/pom.xml, spring-xsuaa-it/pom.xml
Please merge after #179 has been merged.
=> Updated spring boot version in samples and spring-xsuaa-it

spring-xsuaa/README.md
Code sample was not valid java code. I changed it so that it would compile.
=> Improved code sample

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/http/HttpHeader.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/http/HttpHeadersFactory.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/http/HttpHeadersFactoryTest.java
This branch contains a fix for _Token exchange not working_ #200.
=> Token exchange not working

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoderBuilder.java
Plus a little bit refactoring.
=> Make it possible to disable the XsuaaAudienceValidator

java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTestRule.java, java-security-test/src/test/java/com/sap/cloud/security/test/SecurityTestRuleTest.java, java-security/src/main/java/com/sap/cloud/security/spring/adapter/SAPOfflineTokenServicesCloud.java, java-security/src/test/java/com/sap/cloud/security/spring/adapter/SAPOfflineTokenServicesCloudTest.java
Created PR for remarks from last migration PR.
=> Migration remarks

java-security/src/main/java/com/sap/cloud/security/token/AccessToken.java, java-security/src/main/java/com/sap/cloud/security/token/XsuaaToken.java
Created the `AccessToken` Interface and made XsuaaToken implement it. I have left the IasToken unchanged.
=> Created AccessToken Interface

java-security/src/main/java/com/sap/cloud/security/adapter/xs/XSUserInfoAdapter.java
This can be helpful to trace issues in production. If not needed then this PR can be closed.
=> Added more logging information for isInForeignMode

java-security-test/src/main/java/com/sap/cloud/security/test/JwtGenerator.java, java-security/src/main/java/com/sap/cloud/security/adapter/spring/SAPOfflineTokenServicesCloud.java, java-security/src/main/java/com/sap/cloud/security/token/AbstractToken.java, java-security/src/main/java/com/sap/cloud/security/token/AccessToken.java, java-security/src/main/java/com/sap/cloud/security/token/SapIdToken.java, java-security/src/main/java/com/sap/cloud/security/token/ScopeConverter.java, java-security/src/main/java/com/sap/cloud/security/token/Token.java, java-security/src/main/java/com/sap/cloud/security/token/XsuaaScopeConverter.java, java-security/src/main/java/com/sap/cloud/security/token/XsuaaToken.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidatorTest.java
Enforcing uniqueness in data lists by using sets.
=> Sets when data is unique

java-security-test/src/test/java/com/sap/cloud/security/test/SecurityTestRuleTest.java
Rewritten test so that it can work without relying on JsonWebKeySet
=> Adapt tests

samples/deploy_and_test.py
This PR adds a python script to the samples which runs the samples as end2end tests.
=> Semi automated sample testing

java-security-test/src/test/java/com/sap/cloud/security/test/JwtGeneratorTest.java
I have fixed the test setup for the oidc jkws endpoint discovery test. I took the test data from the vcap.json file.
To be able to pass the token validation the issuer needed to be set to _https://app.auth.com_ instead of _https://auth.com_. I am not sure if this is correct or the validation is not flexible enough here.
=> Fixed test setup for oidc jkws endpoint discovery test

samples/deploy_and_test.py
This PR makes the test script more robust, creates more and better error messages and exits sooner in case something goes wrong.
=> Test script improvements

samples/deploy_and_test.py, samples/spring-security-basic-auth/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java
This PR contains little improvements and the test cases for the remaining samples.
=> Finished test script

java-api/src/main/java/com/sap/cloud/security/token/SecurityContext.java, java-security-test/src/main/java/com/sap/cloud/security/test/JwtGenerator.java, java-security/src/main/java/com/sap/cloud/security/token/XsuaaToken.java, java-security/src/test/java/com/sap/cloud/security/token/XsuaaTokenTest.java
Various improvements for build pack integration
=> Improvements for buildpack integration

java-security-test/src/main/java/com/sap/cloud/security/test/JwtGenerator.java, samples/java-security-usage/pom.xml, samples/java-tokenclient-usage/pom.xml, samples/sap-java-buildpack-api-usage/pom.xml, samples/spring-security-basic-auth/pom.xml, samples/spring-security-xsuaa-usage/pom.xml, samples/spring-webflux-security-xsuaa-usage/pom.xml
Remarks from PR #253  and harmonisation of  the version variable name of the samples that use the library. In some pom.xml files the build block occurred before the dependency block. I moved it below the dependency block so that it is consistent across the samples.
=> Version harmonisation and review remarks

api/src/main/java/com/sap/xsa/security/container/XSUserInfoException.java
This reflects the current state of java-container-security.
=> Changes XSUserInfoException from Exception to RuntimeException

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaResourceServerJwkAutoConfigurationTest.java
=> #184 Replaced deprecated NimbusJwtDecoderJwkSupport

pom.xml, samples/spring-security-basic-auth/pom.xml, samples/spring-security-xsuaa-usage/pom.xml, samples/spring-webflux-security-xsuaa-usage/pom.xml
Spring Boot 2.2.6.RELEASE -> 2.3.0.RELEASE
Spring Core 5.2.5.RELEASE -> 5.2.6.RELEASE
Spring Security 5.3.1.RELEASE -> 5.3.2.RELEASE
Spring Security OAuth2 2.4.0.RELEASE -> 2.4.1.RELEASE
Test script ran successfully!
=> Update Spring dependencies

pom.xml, samples/sap-java-buildpack-api-usage/pom.xml, token-client/pom.xml, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/http/HttpHeaders.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/CacheConfiguration.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/Cacheable.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceClientCredentialsTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceRefreshTokenTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceUserTokenTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/http/HttpHeadersTest.java
This PR adds a Cache to the token client. The cache can be configured and disabled for the token service.
=> Token client cache

.github/workflows/maven.yml, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidator.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidatorForCloneTokenTest.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidatorTest.java
..to the validation result description in the audience validation in spring-xsuaa.
=> Add allowed audiences

java-security/src/test/java/com/sap/cloud/security/adapter/xs/XSUserInfoAdapterIntegrationTest.java, java-security/src/test/java/com/sap/cloud/security/servlet/XsuaaTokenAuthenticatorTest.java, token-client/README.md, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOidcConfigurationService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2ServiceException.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/SpringOidcConfigurationService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/http/HttpHeaders.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/CacheConfiguration.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/util/TokenLogger.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/util/TokenLoggerTest.java
This PR improves the logging so that the requirements of #292 are fulfilled.
It also adds a TokenLogger util class that lets you safely log token content for debugging purposes.
=> Improved logging

docs/Troubleshooting_JsonClasspathIssues.md
Explain json issues in more detail and add version conflict issue to description
=> Update json troubleshooting

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/XsuaaJwtIssuerValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/XsuaaJwtIssuerValidatorTest.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoderTest.java
=> refactor jku validation

samples/sap-java-buildpack-api-usage/README.md, samples/sap-java-buildpack-api-usage/manifest.yml, samples/sap-java-buildpack-api-usage/pom.xml, samples/sap-java-buildpack-api-usage/src/main/java/sample/sapbuildpack/xsuaa/HelloTokenServlet.java
Can be merged as soon as this library is integrated in the SAP java buildpack
=> Updated buildpack sample

java-security/src/main/java/com/sap/cloud/security/config/OAuth2ServiceConfigurationBuilder.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtValidatorBuilderTest.java
=> Implement hashCode and equals for OAuth2ServiceConfigurationImpl

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidatorTest.java
=> JwtAudienceValidator should also compare client ids

java-security/Migration_SAPJavaBuildpackProjects.md
Added a section that describes how to find out the buildpack version that is being used.
=> Extend troubleshoot section in migration guide

samples/sap-java-buildpack-api-usage/approuter/package.json, samples/spring-security-xsuaa-usage/approuter/package.json, samples/spring-webflux-security-xsuaa-usage/approuter/package.json
Updated from ^6.8.2 to ^8.2.0.
I have run the samples using the script and everything worked as expected!
=> Update approuter version in samples

samples/deploy_and_test.py
=> Python script 2fa

troubleshooting/logcollector/cf-logcollector.ps1
cf https://github.com/SAP/cloud-security-xsuaa-integration/issues/344
=> Update cf-logcollector.ps1 to fix Issue 344

samples/spring-security-xsuaa-usage/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java, spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/extractor/IasXsuaaExchangeBrokerTest.java, spring-xsuaa/README.md, spring-xsuaa/pom.xml, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/IasXsuaaExchangeBroker.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/TokenBrokerResolver.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/TokenUtil.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/XsuaaToken.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/extractor/IasXsuaaExchangeBrokerTest.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/extractor/TokenUtilTest.java
support usage of com.sap.cloud.security.token.InvalidTokenException without token-client module #430
=> add java-api dependency to spring-xsuaa

java-security/pom.xml
support both junit5 and junit4 tests with surefire plugin
=> Junit Engine fix

samples/spring-security-xsuaa-usage/src/main/java/sample/spring/xsuaa/TestController.java
replacement for this one
https://github.com/SAP/cloud-security-xsuaa-integration/pull/441/files
=> spring-xsuaa token-client usage for multi-tenant usage

spring-xsuaa-test/src/main/java/com/sap/cloud/security/xsuaa/test/JwtGenerator.java, spring-xsuaa-test/src/test/java/com/sap/cloud/security/xsuaa/test/JwtGeneratorTest.java
prefill "ext_atr" "enhancer" with XSUAA
=> Jwt generator enhancement

.github/workflows/maven.yml, samples/deploy_and_test.py, samples/java-security-usage-ias/src/main/java/com/sap/cloud/security/samples/ias/IasSecurityFilter.java
- the service and service key was not successfully deleted
=> CI and python script should include java-security-sample-ias

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtSignatureValidator.java
should be checking oidcConfigurationService instead of tokenKeyService
=> Update oidcConfigurationService assertion in JwtSignatureValidator

samples/sap-java-buildpack-api-usage/approuter/package.json, samples/spring-security-xsuaa-usage/approuter/package.json, samples/spring-webflux-security-xsuaa-usage/approuter/package.json
Hi @liga-oz 
this change is not urgent! Would you mind to test manually the three example via approuter?
At least these ones:
- samples/sap-java-buildpack-api-usage/ and
-  samples/spring-security-xsuaa-usage
according to the README.md
Thx!
=> update approuter version to 9.x -> 10.4

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefault.java, token-client/README.md
=> update docu for externally managed private key provisioning

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/TokenBrokerResolver.java
For TokenBrokerResolver url was not resolved correctly for X.509 authentication method.
=> Fix url issue when using X.509

java-security-it/pom.xml, java-security-it/src/test/java/com/sap/cloud/security/test/integration/XsuaaIntegrationTest.java, java-security-it/src/test/java/com/sap/cloud/security/test/performance/JavaSecurityPerformanceIT.java, java-security-it/src/test/java/com/sap/cloud/security/test/performance/SpringSecurityPerformanceIT.java, java-security-it/src/test/java/com/sap/cloud/security/test/performance/SpringXsuaaPerformanceIT.java
- fixes XsuaaIntegrationTest.java
- adds performance tests for spring-security module
=> Performance tests

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenResponse.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenServiceConstants.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/XsuaaTokenFlows.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenResponseTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceClientCredentialsTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceJwtBearerTokenTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServicePasswordTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceRefreshTokenTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceUserTokenTest.java
=> Expose token_type in OAuth2TokenResponse

CHANGELOG.md, token-client/src/main/java/com/sap/cloud/security/client/DefaultHttpClientFactory.java, token-client/src/main/java/com/sap/cloud/security/mtls/SSLContextFactory.java, token-client/src/test/java/com/sap/cloud/security/mtls/SSLContextFactoryTest.java
fixes #621  (cloud sdk HttpDestinationProperties)
=> SSLContextFactory.createKeyStore(ClientIdentity)

env/src/main/java/com/sap/cloud/security/config/OAuth2ServiceConfigurationBuilder.java, java-api/src/main/java/com/sap/cloud/security/config/CredentialType.java, java-api/src/main/java/com/sap/cloud/security/config/cf/CFConstants.java, spring-security/src/test/java/com/sap/cloud/security/spring/config/IdentityServiceConfigurationTest.java, spring-security/src/test/java/com/sap/cloud/security/spring/config/OAuth2ServiceConfigurationPropertiesTest.java, spring-security/src/test/java/com/sap/cloud/security/spring/config/XsuaaServiceConfigurationTest.java, token-client/src/main/java/com/sap/cloud/security/mtls/SSLContextFactory.java
=> Adapt IAS for x509

spring-security/src/main/java/com/sap/cloud/security/spring/autoconfig/HybridAuthorizationAutoConfiguration.java, spring-security/src/main/java/com/sap/cloud/security/spring/autoconfig/HybridIdentityServicesAutoConfiguration.java, spring-security/src/main/java/com/sap/cloud/security/spring/autoconfig/XsuaaTokenFlowAutoConfiguration.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/autoconfiguration/SpringHttpClient.java
=> [CAP] auto-configurations must be public 

.reuse/dep5
=> Attach copyright to all Dockerfile and deployment.yml

java-api/pom.xml, java-api/src/main/java/com/sap/cloud/security/token/Token.java, java-api/src/test/java/com/sap/cloud/security/servlet/HybridTokenFactory.java, java-api/src/test/java/com/sap/cloud/security/servlet/HybridTokenFactoryMock.java, java-api/src/test/java/com/sap/cloud/security/token/TokenTest.java, java-api/src/test/resources/META-INF/services/com.sap.cloud.security.token.TokenFactory, token-client/pom.xml, token-client/src/main/java/com/sap/cloud/security/client/DefaultHttpClientFactory.java, token-client/src/main/java/com/sap/cloud/security/client/HttpClientFactory.java, token-client/src/test/java/com/sap/cloud/security/client/HttpClientFactoryTest.java, token-client/src/test/java/com/sap/cloud/security/client/TestHttpClientFactory.java, token-client/src/test/resources/META-INF/services/com.sap.cloud.security.client.HttpClientFactory
=> Prioritize SPI loading of custom implementations

token-client/README.md
=> Enhance token-client docu explaining how to customize OAuth2ServiceConfiguration

samples/java-security-usage-ias/README.md, samples/java-security-usage/README.md, samples/spring-security-hybrid-usage/README.md
=> Incorporate HowToFetchToken.md into sample READMEs

.github/workflows/maven.yml, env/pom.xml, java-api/pom.xml, java-security-it/src/test/java/com/sap/cloud/security/test/integration/XsuaaMultipleBindingsIntegrationTest.java, java-security/pom.xml, pom.xml, spring-security/pom.xml, spring-xsuaa-mock/pom.xml, spring-xsuaa-test/pom.xml, spring-xsuaa/pom.xml, token-client/pom.xml
=> Ensure compatibility with java 11

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefault.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefaultTest.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationFromEnvTest.java
=> XsuaaServiceConfigurationDefault supports access to other credentials

spring-security/src/main/java/com/sap/cloud/security/spring/token/authentication/JwtDecoderBuilder.java, spring-xsuaa/pom.xml, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationFromEnvTest.java
- [spring-xsuaa] fixes mvn test run, by using another System Stub and jupiter
- [spring-security] formats jwtDecoderBuilder
=> Fix mvn Test Run with System Stubs

spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaAutoConfigurationTest.java
=> [spring-xsuaa] Improve test coverage

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidatorTest.java
=> allow IAS token issuer claims without https schema

pom.xml
=> remove explicit jackson-databind dependency (version upgraded by spring)

CHANGELOG.md, java-api/src/main/java/com/sap/cloud/security/token/AccessToken.java, java-api/src/main/java/com/sap/cloud/security/token/Token.java, java-security/src/main/java/com/sap/cloud/security/adapter/xs/XSUserInfoAdapter.java, spring-security-compatibility/src/main/java/com/sap/cloud/security/comp/XsuaaTokenComp.java, spring-security-compatibility/src/test/java/com/sap/cloud/security/comp/XsuaaTokenCompTest.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/XsuaaToken.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/XsuaaTokenTest.java
=> return null when token claim is not present

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtSignatureValidator.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyService.java
closes  #921
alert suppression should work once the PR is merged https://lgtm.com/help/lgtm/automated-code-review-faqs#why-automated-code-review-reports-misses-alert
=> Suppress lgtm alerts

samples/spring-security-basic-auth/pom.xml, samples/spring-security-hybrid-usage/pom.xml, samples/spring-security-xsuaa-usage/pom.xml, samples/spring-webflux-security-xsuaa-usage/pom.xml, spring-xsuaa-starter/pom.xml
Fix for https://nvd.nist.gov/vuln/detail/CVE-2022-25857
=> Patch CVE 2022-25857

env/src/test/java/com/sap/cloud/security/json/DefaultJsonObjectTest.java, etc/suppression.xml
=> Test CVE 2022 45688 vulnerability

README.md, java-security-test/README.md, java-security/Migration_SAPJavaBuildpackProjects.md, java-security/Migration_SAPJavaBuildpackProjects_V2.md, java-security/README.md, samples/spring-security-basic-auth/README.md, samples/spring-security-xsuaa-usage/README.md, spring-xsuaa-it/pom.xml, spring-xsuaa/Migration_JavaContainerSecurityProjects.md, spring-xsuaa/README.md, token-client/README.md, token-client/pom.xml
=> Fix token client logback scope

env/pom.xml
=> Exclude slf4j-api 2.x from transitive dependencies

README.md
Fix some small typos and write auth code flow in a bit more detail
=> README.md Suggestions

token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/ClientCredentialsTokenFlow.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/JwtBearerTokenFlow.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/XsuaaTokenFlowsUtils.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/JwtBearerTokenFlowTest.java
* add back the zone id support
* add back the authorization attribute az_attr support
=> make JwtBearerTokenFlow consistent with the other token flows

.github/workflows/maven-build-2.x.yml
Replacing the obsolete 'adopt' runtime
Closes #1163
=> Use temurin runtime in workflow (v2)

.github/workflows/maven-build.yml
Replacing the obsolete 'adopt' runtime
Closes #1163
=> Use temurin runtime in workflow (main-dev)

.github/workflows/maven-build.yml
Replacing the obsolete 'adopt' runtime
Closes #1163
=> Use temurin runtime in workflow

CHANGELOG.md, env/src/main/java/com/sap/cloud/security/json/DefaultJsonObject.java, java-api/src/main/java/com/sap/cloud/security/json/JsonObject.java, java-security/src/main/java/com/sap/cloud/security/token/ScopeConverter.java, java-security/src/main/java/com/sap/cloud/security/token/XsuaaScopeConverter.java, java-security/src/main/java/com/sap/cloud/security/token/XsuaaToken.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/jwt/Base64JwtDecoder.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/jwt/DecodedJwt.java
=> make XsuaaToken serializable

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2ServiceException.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenService.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/OAuth2ServiceExceptionTest.java
=> add http headers to OAuth2ServiceException constructor and add getter

java-security/src/main/java/com/sap/cloud/security/token/XsuaaToken.java, java-security/src/test/java/com/sap/cloud/security/token/XsuaaTokenTest.java
=> Fix NPE when accessing XsuaaToken.getPrincipal() and grantType is null

CHANGELOG.md, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JsonWebKeyConstants.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JsonWebKeySet.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JsonWebKeySetFactory.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtSignatureValidator.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtValidatorBuilder.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCache.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/SapIdJwtSignatureValidator.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/XsuaaJwtSignatureValidator.java, java-security/src/test/java/com/sap/cloud/security/servlet/IasTokenAuthenticatorTest.java, java-security/src/test/java/com/sap/cloud/security/servlet/IasTokenAuthenticatorX509Test.java, java-security/src/test/java/com/sap/cloud/security/servlet/XsuaaTokenAuthenticatorTest.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/IdTokenSignatureValidatorTest.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtValidatorBuilderTest.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCacheTest.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/SapIdJwtSignatureValidatorTest.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/XsaJwtSignatureValidatorTest.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/XsuaaJwtSignatureValidatorTest.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/http/HttpHeaders.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyServiceTest.java
=> Add azp header for Identity JWKS Retrieval

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenService.java, token-client/src/test/java/com/sap/cloud/security/client/DefaultHttpClientFactoryTest.java
Small fixes for next release (unit test and documentation)
=> Refactoring 2.15.1

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenService.java, token-client/src/test/java/com/sap/cloud/security/client/DefaultHttpClientFactoryTest.java
Small fixes for next release (unit test and documentation)
See #1335
=> Refactoring 3.3.0

env/src/main/java/com/sap/cloud/security/config/ServiceBindingMapper.java
=> Change fallback plan from "APPLICATION" to "application"

java-api/src/main/java/com/sap/cloud/security/token/SecurityContext.java, java-security/src/test/java/com/sap/cloud/security/token/SecurityContextTest.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyService.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyServiceTest.java
+ change service plan getter to List<String> from String[]
=> Change service plan parsing to account for quotes around names

pom.xml
update spring dependencies in one PR to maintain compatibility
=> update spring core, boot and security versions

env/pom.xml, java-api/pom.xml, java-security-test/pom.xml, java-security/pom.xml, spring-security-compatibility/pom.xml, spring-security/pom.xml, spring-xsuaa-test/pom.xml, spring-xsuaa/pom.xml, token-client/pom.xml
see https://stackoverflow.com/questions/76305897/maven-build-fails-after-upgrading-to-maven-source-plugin-from-3-2-1-to-3-3-0
=> fix maven-source-plugin configuration

env/pom.xml, pom.xml, spring-security/pom.xml, spring-xsuaa/pom.xml
Bump com.nimbusds:nimbus-jose-jwt from 10.0.2 to 10.2
Bump io.github.hakky54:logcaptor from 2.10.1 to 2.10.2
Bump uk.org.webcompere:system-stubs-jupiter from 2.1.7 to 2.1.8
Bump com.github.spotbugs:spotbugs-annotations from 4.9.2 to 4.9.3
=> Updating several dependencies
