spring-xsuaa/src/main/java/com/sap/xs2/security/container/UserInfoAuthenticationConverter.java
This is required, when i would like to add xs.user.attributes into the list of Authorities.
=> Make UserInfoAuthenticationConverter.extractAuthorities enhancable

etc/eclipse_settings.xml, spring-xsuaa/src/main/java/com/sap/xs2/security/container/UserInfo.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTest.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTestClientCredentials.java, spring-xsuaa/src/test/java/com/sap/xs2/security/container/UserInfoTestSAML.java
- user/<origin>/<logonName>
- client/<clientid>/<logonName>
further changes:
- UserInfo provides static method "getUniquePrincipalName" that can be
called by consumers
- added /etc/eclipse_settings.xml from xsuaa for contributers
fix intendations
=> Fix: principal / client name must be unique

pom.xml, spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/XsuaaMockWebServer.java, spring-xsuaa-mock/src/test/java/com/sap/cloud/security/xsuaa/mock/ApplicationTest.java, spring-xsuaa-mock/src/test/java/com/sap/cloud/security/xsuaa/mock/XsuaaMockWebServerSpringBootTest.java, spring-xsuaa-test/README.md, spring-xsuaa-test/src/main/java/com/sap/cloud/security/xsuaa/test/JwtGenerator.java, spring-xsuaa-test/src/test/java/com/sap/cloud/security/xsuaa/test/JwtGeneratorTest.java
This change relates to @sawoz  proposal of making use of these two maven plugins:
- [Maven `code.revelc.net-formatter` plugin](https://code.revelc.net/formatter-maven-plugin/usage.html)  that considers [our formatting settings](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/etc/eclipse_settings.xml) 
- [Maven `code.revelc.net-impSort` plugin](https://code.revelc.net/impsort-maven-plugin/index.html) to ensure import ordering and removal of unused imports
I've applied the formatting only on "my" modules `spring-xsuaa-test` and  `spring-xsuaa-mock`. There is no difference now from applying it as part of my Ide.
use on the command line on top level or as part of sub module:
```
mvn formatter:format
```
fixes #44 
refers to #42
fixes #54
=> Introduce mvn formatter goal and other fixes

spring-xsuaa-test/src/main/java/com/sap/cloud/security/xsuaa/test/JwtGenerator.java, spring-xsuaa-test/src/test/java/com/sap/cloud/security/xsuaa/test/JwtGeneratorTest.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidator.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidatorTest.java
[XsuaaAudienceValidator.allowedAudiences()](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidator.java#L54)
- should not return blanks ("") as audience in the list (this can happen, if the xsuaa.xsappname is "")
- should not return duplicates
Related issue:
#62
=> Fix allowed audiences

spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/extractor/BasicCredentialExtractorTest.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/TokenBrokerResolver.java
With this change two kind of tokens are supported: Oauth and basic/client-credentials.
E.g. in case the "Authorization" header is not provided, and basic or client-credentials is supported it tries to return the password or client-credentials token.
=> extractToken should support oauth and/or client credentials

CHANGELOG.md, spring-xsuaa-it/pom.xml, spring-xsuaa-it/src/main/java/testservice/api/basic/SecurityConfiguration.java, spring-xsuaa-it/src/main/java/testservice/api/basic/TestController.java, spring-xsuaa-it/src/main/java/testservice/api/nohttp/MyEventHandler.java, spring-xsuaa-it/src/main/java/testservice/api/nohttp/SecurityConfiguration.java, spring-xsuaa-it/src/main/java/testservice/api/v1/SecurityConfiguration.java, spring-xsuaa-it/src/main/java/testservice/api/v1/TestController.java, spring-xsuaa-it/src/main/resources/application-uaamock.yml, spring-xsuaa-it/src/main/resources/application.yml, spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/extractor/BasicCredentialExtractorTest.java, spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/InitializeSecurityContextTest.java, spring-xsuaa-it/src/test/java/testservice/api/InitializeSecurityContextTest.java, spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/MockXsuaaServiceConfiguration.java, spring-xsuaa/README.md, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java, spring-xsuaa/src/main/java/com/sap/xs2/security/container/SecurityContext.java
In case of non-HTTP requests, you may need to initialize the Spring SecurityContext with a JWT token you've received from a message or you've requested from XSUAA directly.
**Prerequisite**:   
You need to initialize a `JwtDecoder` bean, as explained [here](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/samples/spring-security-xsuaa-usage/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java), using the `XsuaaJwtDecoderBuilder` class.
**Then, initialize Security Context**:
```
@Autowired
JwtDecoder jwtDecoder;
public void initializeSecurityContext() {
Jwt jwtToken = jwtDecoder.decode(<your encoded jwt token String>);
SecurityContext.init(XSAPPNAME, jwtToken, true);
}
```
By default the SecurityContext is initialized for your current Thread. I.e. you can access …
=> Initialization of Spring SecurityContext for non HTTP requests

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServicePropertySourceFactory.java
Aims to solve issue #77 
Simply adding a `null` check to avoid the `NullPointerException` as explained in the issue. Also changed the expression that checked if the filename was not empty to use the `isEmpty` method.
=> add null check to avoid NullPointerException when resource is reactive

spring-xsuaa-it/src/main/java/testservice/api/basic/SecurityConfiguration.java, spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/extractor/BasicAuthenticationValidationIT.java, spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaTokenValidationIT.java, spring-xsuaa-it/src/test/java/testservice/api/InitializeSecurityContextTest.java, spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/MockXsuaaServiceConfiguration.java, spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/XsuaaMockWebServer.java, spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/XsuaaRequestDispatcher.java, spring-xsuaa-mock/src/test/java/com/sap/cloud/security/xsuaa/mock/XsuaaMockWebServerTest.java, spring-xsuaa-test/src/main/java/com/sap/cloud/security/xsuaa/test/JwtGenerator.java, spring-xsuaa-test/src/test/java/com/sap/cloud/security/xsuaa/test/JwtGeneratorTest.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfiguration.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefault.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/AuthenticationToken.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/Token.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/TokenClaims.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/TokenImpl.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java
Use jku of token to retrieve token keys instead of building
url.
Keep JWTGenerator compatible by setting JKU in token in transparent way.
Assumption: Mock xsuaa url is 'http://localhost:33195'
=> Use jku of token to retrieve keys

spring-xsuaa-it/src/main/java/testservice/api/basic/SecurityConfiguration.java, spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaTokenValidationIT.java, spring-xsuaa-mock/README.md, spring-xsuaa-mock/pom.xml, spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/MockXsuaaServiceConfiguration.java, spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/XsuaaMockWebServer.java, spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/autoconfiguration/XsuaaMockAutoConfiguration.java, spring-xsuaa-mock/src/main/resources/META-INF/spring.factories, spring-xsuaa-mock/src/test/java/com/sap/cloud/security/xsuaa/mock/ApplicationTest.java, spring-xsuaa-mock/src/test/java/com/sap/cloud/security/xsuaa/mock/XsuaaMockWebServerSpringBootTest.java, spring-xsuaa-mock/src/test/java/com/sap/cloud/security/xsuaa/mock/autoconfiguration/XsuaaMockAutoConfigurationTest.java, spring-xsuaa-mock/src/test/resources/application-uaamock.properties, spring-xsuaa/README.md, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java
with jku introduction with PR #100 the lib became incompatible as tests had 
- either to configure XsuaaMockAutoConfiguration
```@SpringBootTest(classes = { XsuaaAutoConfiguration.class, XsuaaMockAutoConfiguration.class })``` or
- or to configure xsuaa.uaadomain via properties
```@SpringBootTest(properties = { "xsuaa.url=${mockxsuaaserver.url}", "xsuaa.uaadomain=localhost}" })```
I decided to introduce auto-configuration for XsuaaMockAutoConfiguration, as also documented in the Readme.
Further changes:
- improve log messages
- document new mvn dependencies
=> [version 1.5.0] introduce auto-configuration for mock server configuration

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/OAuth2AuthenticationConverter.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/OAuth2TokenAuthenticationConverterTest.java
Requiered to make the authentication work, even if it looks redudant.
=> Set scopes for OAuth2Authentication

samples/spring-webflux-security-xsuaa-usage/pom.xml, samples/spring-webflux-security-xsuaa-usage/src/main/java/sample/spring/webflux/xsuaa/TestController.java, samples/spring-webflux-security-xsuaa-usage/src/test/java/sample/spring/webflux/xsuaa/ApplicationTest.java, samples/spring-webflux-security-xsuaa-usage/src/test/java/sample/spring/webflux/xsuaa/TestControllerTest.java, samples/spring-webflux-security-xsuaa-usage/src/test/java/sample/spring/webflux/xsuaa/mock/XsuaaMockPostProcessor.java, samples/spring-webflux-security-xsuaa-usage/src/test/resources/META-INF/spring.factories, samples/spring-webflux-security-xsuaa-usage/src/test/resources/application.properties, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefault.java
* Adding `spring-xsuaa-test` and `spring-xsuaa-mock` to webflux sample project.
* reduce verbosity of `TestController`
* Added authorized and unauthorized tests to `TestController` 
p.s. the `XsuaaServiceConfigurationDefault` wasn't building correctly the url from the `getTokenKeyUrl`. I wasn't setting the `uaaUrl` as I was expecting the mock to inject it.  Therefore, changed it to get the value from the method instead of accessing directly the attribute.
=> Add further testcase to webflux sample application

CHANGELOG.md, spring-xsuaa-it/src/main/java/testservice/api/nohttp/MyEventHandler.java, spring-xsuaa/src/main/java/com/sap/xs2/security/container/SecurityContext.java
- preparation for 2.0.0
Considers this issue:
- https://github.com/SAP/cloud-security-xsuaa-integration/issues/119
=> Deprecates SecurityContext to avoid issues with Security Container lib

spring-xsuaa-mock/src/main/java/com/sap/cloud/security/xsuaa/mock/XsuaaMockWebServer.java, spring-xsuaa-test/src/main/java/com/sap/cloud/security/xsuaa/test/JwtGenerator.java
This pull requests enables users to override the port the XsuaaMockWebServer listens to and to override the port the JwtGenerator uses to connect to the web server.
=> Make ports configurable

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java
Using try-with-resources Statement to automatically close the connections of executed requests. Additional calling of `close` on the httpClient will throw` java.net.SocketException: Socket is closed`.
=> Closing HTTP requests

pom.xml, spring-xsuaa/pom.xml
I have moved the exclusion rule for spring-security-oauth2 to the parent pom and added exclusions for vulnerable jackson libraries (CVE-2019-10202) that we don't actually use. I have successfully tested this with all the samples. 
relates to NGPBUG-98555
=> Excluded vulnerable jackson library

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServicePropertySourceFactory.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServicesParser.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/CustomPropertySourceFactoryTest.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServicePropertySourceFactoryTest.java
In this PR 
- the `PropertySourceFactory` is cleaned up and allows the creation of a PropertySource for xsuaa Properties. 
- the `XsuaaServicesParser` offers a new method `parseCredentials()` that parses a VCAP_SERVICES json string and returns all credential fields as Properties.
With that CAP or others can overwrite all or some xsuaa properties with their own values, as documented in the `CustomPropertySourceFactoryTest` test class:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/3fe1fa52e902a3dc4a6886eca42bc642390a140b/spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/CustomPropertySourceFactoryTest.java
=> PropertySourceFactory should support custom properties

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaAutoConfiguration.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaAutoConfigurationTest.java
The default property source can now be disabled by setting the property `disable-default-property-source` to `true`.
SECAUTH-524
=> Disable default property source

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenServiceConstants.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/RequestParameterBuilder.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceJwtBearerTokenTest.java
In case a trust is created between IAS and XSUAA, then you can use this to replace an IAS OIDC token with an XSUAA Access Token.
Furthermore its possible to attach a Role Collection to this IAS Identity Provider in the cockpit to receive scopes as part of the returned access token.
=> Implemented JWT bearer token grant support

java-security-test/src/main/java/com/sap/cloud/security/test/JwtGenerator.java
Because they are not standard compliant. The definition of the base64 encoding that is used to create JWT-Tokens is defined as follows in [rfc7515](https://tools.ietf.org/html/rfc7515):
> Base64 encoding using the URL- and filename-safe character set
defined in Section 5 of RFC 4648 [RFC4648], with all trailing '='
characters omitted (as permitted by Section 3.2) and without the
inclusion of any line breaks, whitespace, or other additional
characters.
The change is simple, we can just encode without the padding. The java base64 decoder automatically detects the presence (or absence) of base64 paddings. So we do not run into compatibility issues with newly generated tokens that lack paddings.
=> Remove base64 paddings in jwt tokens

java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTestRule.java
I'm a developer of the [SAP Cloud SDK](https://community.sap.com/topics/cloud-sdk) and currently I'm creating a sample application and different test setups for best practices to show the integration of both libraries.
In order to enable the Cloud SDK within applications served by the internal Jetty container during tests, we would need the consumer to be able to attach our filter class.
Before:
```java
@ClassRule
public static SecurityTestRule rule =
SecurityTestRule.getInstance(Service.XSUAA)
.useApplicationServer()
.addApplicationServlet(TestServlet.class, "/app");
```
After:
```java
@ClassRule
public static SecurityTestRule rule =
SecurityTestRule.getInstance(Service.XSUAA)
.useApplicationServer()
.addApplicationServlet(TestServlet.class, "/app") …
```
=> Increase visibility of SecurityTestRule#addApplicationServletFilter

java-security-test/src/main/java/com/sap/cloud/security/test/JwtGenerator.java, java-security-test/src/test/java/com/sap/cloud/security/test/JwtGeneratorTest.java, java-security-test/src/test/java/com/sap/cloud/security/test/RSAKeysTest.java
The paths to the key files for `RSAKeys.fromKeyFiles` and `SecurityTestRule.setKeys` must be given as resources path. 
`JwtGenerator.withClaimsFromFile` should also use the resources path. This PR enables this.
=> withClaimsFromFile should handle file path just like RSAKeys

java-security-test/src/main/java/com/sap/cloud/security/test/jetty/JettyTokenAuthenticator.java, java-security/src/main/java/com/sap/cloud/security/servlet/AbstractTokenAuthenticator.java, samples/java-security-usage/src/main/java/com/sap/cloud/security/samples/tmp/JettyTokenAuthenticator.java
Sending an error response commits the response which prevents library users to leverage their own error response mechanism.
=> The AbstractTokenAuthenticator should not send an error response

java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTest.java, java-security-test/src/test/java/com/sap/cloud/security/test/SecurityTestTest.java
This prevents issues when the static SecurityTestRule is reused in many classes.
In my machine it took WireMock between 20ms and 100ms to shutdown. This code checks every 50ms if the server has been shutdown and sleeps otherwise. I also added a check so that this check is only done 100 times. This means that this will never block longer than 5 seconds.
=> Waiting for WireMock to shutdown 

java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTest.java
Catching an `InterruptedException` resets the current thread's interrupted state. It is best practice to either re-throw the exception or at least exit and set the thread's interrupted state and not 'swallow' the exception. This is described [here](https://www.ibm.com/developerworks/java/library/j-jtp05236/index.html?ca=drs-#2.1).
=> Better InterruptedException handling

samples/deploy_and_test.py, samples/spring-security-xsuaa-usage/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java
Also the security configuration needed another `antMatchers`. Without this line the `requestRefreshToken` will always be denied (403).
=> Added refresh token flow test

java-security/Migration_SpringSecurityProjects.md
Updated the Migration_SpringSecurityProjects file by removing non required dependency and removing the version of the xsd files in the spring-security.xml example.
=> Remove xsd version, remove spring-aop

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidator.java
Every invalid validation result object will log its message when it is created.
If an invalid validation is created and then thrown away, the log entry will
still remain. This is confusing because the validation might be valid but the
log states otherwise.
=> Create validation results lazy

api/src/main/java/com/sap/xsa/security/container/XSUserInfo.java, java-security/src/main/java/com/sap/cloud/security/adapter/xs/XSUserInfoAdapter.java, java-security/src/test/java/com/sap/cloud/security/adapter/xs/XSUserInfoAdapterTest.java
Add the `requestTokenForUser` to `XSUserInfoAdapter`.
This PR also includes a bug fix that has not been noticed yet.
Instead of a client credentials flow a user token flow was perform when `requestTokenForClient` was called. This is fixed and tested now!
=> Add requestTokenForUser to XSUserInfoAdapter

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenServiceConstants.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/ClientCredentialsTokenFlow.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/UserTokenFlow.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/ClientCredentialsTokenFlowTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/UserTokenFlowTest.java
Support reducing the scope of created tokens by adding the scope attribute to the request.
=> Support scope parameter in token-client

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCache.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCacheTest.java
This PR changes that exceptions are not thrown anymore when the cache size or the cache duration is set too low.
=> Implement fallback cache size / duration

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCache.java
In case a user tries to configure a cache that is not allowed (too low cache duration or size), the log still would state that the cache was configured this way but it is actually not.
=> Log actual cache configuration and not the unchecked one

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidatorTest.java
this is relevant for apps that migrate from java-security-container client lib and were called with a token of grant type "user_token", which does not provide `aud` claim.
=> [java-security] derive audiences from scopes

java-api/pom.xml, java-security-test/pom.xml, java-security/pom.xml, pom.xml, samples/java-tokenclient-usage/pom.xml, samples/sap-java-buildpack-api-usage/pom.xml, samples/spring-security-basic-auth/pom.xml, samples/spring-security-xsuaa-usage/pom.xml, samples/spring-webflux-security-xsuaa-usage/pom.xml, spring-xsuaa-mock/pom.xml, spring-xsuaa-test/pom.xml, spring-xsuaa/pom.xml, token-client/pom.xml
This PR moves the configuration of the maven plugins pmd and jacoco into the main pom.xml.
It updates:
- **jacoco-maven-plugin** from `0.8.2` to `0.8.5`
- **maven-pmd-plugin** from `3.10.0` to `3.13.0`
- **dependency-check-maven** from `5.2.2` to `5.3.2`
Also `maven.compiler.source` and `maven.compiler.target` are now set to `1.8` in **sap-java-buildpack-api-usage** and **java-tokenclient-usage** because they would not compile with JDK 11 without this setting.
Now the project compiles fine with JDK 11!
=> Improve maven plugin management

CHANGELOG.md, api/pom.xml, java-api/pom.xml, java-security-test/README.md, java-security-test/pom.xml, java-security/Migration_SAPJavaBuildpackProjects.md, java-security/Migration_SAPJavaBuildpackProjects_V2.md, java-security/Migration_SpringSecurityProjects.md, java-security/README.md, java-security/pom.xml, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidatorTest.java, pom.xml, samples/java-security-usage/pom.xml, samples/java-tokenclient-usage/pom.xml, samples/sap-java-buildpack-api-usage/pom.xml, samples/spring-security-basic-auth/pom.xml, samples/spring-security-xsuaa-usage/pom.xml, samples/spring-webflux-security-xsuaa-usage/pom.xml, spring-xsuaa-it/pom.xml, spring-xsuaa-mock/README.md, spring-xsuaa-mock/pom.xml, spring-xsuaa-starter/pom.xml, spring-xsuaa-test/README.md, spring-xsuaa-test/pom.xml, spring-xsuaa/README.md, spring-xsuaa/pom.xml, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidator.java, token-client/README.md, token-client/pom.xml
Audience Validation should validate to true when `client_id` of broker-clone token matches the trusted client. This is relevant to support tokens of grant type `user_token` that contains no scopes.
=> Ngpbug 120051

java-api/pom.xml, java-security/pom.xml, pom.xml, spring-xsuaa-mock/pom.xml, spring-xsuaa-test/pom.xml, spring-xsuaa/pom.xml, token-client/pom.xml
This PR adds skipping of static code analysis and the maven dependency check when maven is run with -DskipTests
=> Skipe code analysis on skip tests

java-api/src/main/java/com/sap/cloud/security/config/Service.java, java-security/Migration_SAPJavaBuildpackProjects.md, java-security/src/main/java/com/sap/cloud/security/config/OAuth2ServiceConfigurationBuilder.java, java-security/src/main/java/com/sap/cloud/security/json/DefaultJsonObject.java, java-security/src/main/java/com/sap/cloud/security/token/AbstractToken.java, java-security/src/main/java/com/sap/cloud/security/token/validation/CombiningValidator.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtValidatorBuilder.java, java-security/src/test/java/com/sap/cloud/security/token/AbstractTokenTest.java, samples/sap-java-buildpack-api-usage/manifest.yml
This is the simple solution for token logging more information on failed authentication attemps.
Todos:
=> Log token content/jwt validator config on failed authentication

java-security-test/src/main/java/com/sap/cloud/security/test/JwtGenerator.java, java-security-test/src/test/java/com/sap/cloud/security/test/JwtGeneratorTest.java, java-security-test/src/test/java/com/sap/cloud/security/test/TokenValidationIntegrationTest.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidatorTest.java
This also changes the existing validation test so that the defaults of the JwtGenerator are not overridden in the test.
=> Fix wrong DEFAULT_JWKS_URL in JwtGenerator

spring-cas/pom.xml, spring-cas/src/main/java/com/sap/cloud/security/cas/spring/AdcServiceAutoConfiguration.java, spring-cas/src/main/java/com/sap/cloud/security/cas/spring/AdcSpringMethodSecurityAutoConfiguration.java, spring-cas/src/main/java/com/sap/cloud/security/cas/spring/AdcSpringSecurityExpression.java, spring-cas/src/main/java/com/sap/cloud/security/cas/spring/AdcSpringSecurityExpressionHandler.java, spring-cas/src/main/java/com/sap/cloud/security/cas/spring/AdcSpringSecurityExpressionHandlerXsuaa.java, spring-cas/src/main/java/com/sap/cloud/security/cas/spring/MethodSecurityConfiguration.java, spring-cas/src/main/resources/META-INF/spring.factories, spring-cas/src/test/java/com/sap/cloud/security/cas/spring/AdcSpringSecurityExpressionTest.java, spring-cas/src/test/java/com/sap/cloud/security/cas/spring/AutoConfigurationTest.java, spring-cas/src/test/java/com/sap/cloud/security/cas/spring/MethodSecurityConfigurationTest.java
- simplify Auto-configuration MethodSecurityConfiguration in that regard that the interface with lazy load is not required anymore
- rename Autoconfiguation classes
- AdcServiceConfiguration --> AdcServiceAutoConfiguration
- MethodSecurityConfiguration 	--> AdcSpringMethodSecurityAutoConfiguration
- AdcSpringSecurityExpression should not have any dependency to spring-security-oauth2-resource-server
- dependency should only be provided as part of pom.xml
@hassler-d can you please test this with your xsuaa sample?
=> Cas update

java-security/Migration_SAPJavaBuildpackProjects_V2.md, spring-xsuaa/Migration_JavaContainerSecurityProjects.md, token-client/Migration_XSUserInfoRequestToken.md
This PR adds a migration guide that describes how to replace the `requestToken`, `requestTokenForUser` and `requestTokenForClient` methods calls of `(XS)UserInfo` with the `token-client` library.
=> Migration guide for request token via UserInfo

java-api/src/main/java/com/sap/cloud/security/config/CacheConfiguration.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCache.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/TokenKeyCacheConfiguration.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCacheTest.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/Cacheable.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/TokenCacheConfiguration.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenServiceTest.java
This PR adds the possibility to enable cache statistics in the `CacheConfiguration`. Every `Cacheable` can return their specific cache statistic object. 
This PR is motivated by #340
=> Cache statistics

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidator.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaAudienceValidatorTest.java
Recently, I had to debug through `XsuaaAudienceValidator` and I felt that it was partially hard to read. In method `getAllowedAudiences` I had the impression that you have a hard time handling things using Java Lists, but in fact do not want to use the property of ordering at all. Instead, you are busy fixing things afterwards using Java Streams.
Therefore, I'd like to propose this PR making things simpler to read without losing any kind of functionality or quality. The general idea is to not make use of Lists, but to use a (Hash)Set instead. This also sightly will have advantages in terms of performance (in case JWTs do get larger).
Feel free to merge; I do not claim any ownership of my changes, but only want to make things better...
=> Simplifications of XsuaaAudienceValidator

java-security-test/src/test/java/com/sap/cloud/security/test/extension/SecurityTestExtensionTest.java
This added test case checks that it is possible to stub an endpoint using the `SecurityTestContext` after the underlying wiremock server has been already been started.
=> Add test that checks stubbing works after setup

pom.xml
Adding the junit-platform-commons to the dependency management ensures that this specified version will be used. Without explicitly setting the version, third party dependencies might bring junit-platform-commons in an older version. This causes problem when this older version is not compatible with junit-jupiter used in this project.
With this change the performance tests can be run again from java-security-it via `mvn failsafe:integration-test`
**EDIT: I now use the junit 5 bom, see newest [comment](https://github.com/SAP/cloud-security-xsuaa-integration/pull/392#issuecomment-708341269)**
=> Add junit-bom to dependency management

java-security-test/src/main/java/com/sap/cloud/security/test/JwtGenerator.java, java-security-test/src/test/java/com/sap/cloud/security/test/JwtGeneratorTest.java
- IAS provides "zone_uuid" and "user_uuid" 
- XSUAA provides as of now only "zid"
These fields should be prefilled. Applications can override if needed.
=> JwtGenerator should prefill the zone and user with defaults

java-api/pom.xml, java-security/pom.xml
`javax.servlet-api` dependency should always use `provided` scope, as those classes are provided by the Servlet container like Tomcat.
Also add the same dependency on `java-security` as `provided` dependencies are not transitive.
Fixes #427.
=> Fix javax.servlet-api dependency scope

java-security-test/src/test/java/com/sap/cloud/security/test/JwtGeneratorTest.java
The test JwtGeneratorTest  was using RSAPublicKeyImpl
As this is an JDK specific internal class, it fails on some JDKs. Fix is to change to the interface.
=> [fix] Change from internal class RSAPublicKeyImpl to RSAPublicKey in JwtGeneratorTest

spring-xsuaa/pom.xml
nimbus is not required as dependency in spring-xsuaa as all usage have been replaced with org.json, therefore excluding it.
=> exclude nimbus library to resolve security vulnerability

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java
As of org.springframework.security version 5.5.0 AuthenticationServiceException gets no longer handled and does not result into 401 status code. 
But BadJwtException results into InvalidBearerTokenException which then gets mapped to 401 status code as expected.
Further References
- https://github.com/spring-projects/spring-security/issues/9395
- https://github.com/spring-projects/spring-security/commit/0c3754c81133afd33bfdac28569473d8ac2cdaff#diff-eff4fee1a4b87fa8efaa934f4d2383df1c50192c36870d6b51db3bd7ff37d35e
=> XsuaaJwtDecoder raises BadJwtException instead of JwtException

java-security/src/main/java/com/sap/cloud/security/servlet/HybridTokenFactory.java
In our k8s environment the xsuaa service configs can't be automatically derived (even #607 will not change this for now). However, an internal audit-logging library uses this class, which leads to error messages being logged.
I am hoping one can reduce the severity of the log message to `warning` as it is able to continue with some limitations.
What do you think?
=> Reduce log message severity

java-security/README.md, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefault.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServicePropertySourceFactory.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServicesParserTest.java
- cleanup "identityzoneid" as it was never exposed
- `XsuaaServiceConfigurationDefault.hasProperty("apiurl")` returns true if VCAP_SERVICES-xsuaa-credentials contains attribute "apiurl"
- `XsuaaServiceConfigurationDefault.getProperty("apiurl")` returns value from VCAP_SERVICES-xsuaa-credentials-apiurl or null, if attribute does not exist.
closes #601
=> XsuaaServiceConfigurationDefault supports access to other VCAP_SERVICES credentials properties

spring-security/src/main/java/com/sap/cloud/security/spring/token/authentication/XsuaaTokenAuthorizationConverter.java, spring-security/src/test/java/com/sap/cloud/security/spring/token/authentication/XsuaaTokenAuthorizationConverterTest.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/LocalAuthoritiesExtractor.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/TokenAuthenticationConverterTest.java
**Before**
```java
Converter<Jwt, AbstractAuthenticationToken> getJwtAuthenticationConverter() {
TokenAuthenticationConverter converter = new TokenAuthenticationConverter(xsuaaServiceConfiguration);
converter.setLocalScopeAsAuthorities(true);
return converter;
}
```
**New**
```java
Converter<Jwt, AbstractAuthenticationToken> getJwtAuthenticationConverter() {
return new TokenAuthenticationConverter(new MyCustomAuthoritiesExtractor());
}
private static class MyCustomAuthoritiesExtractor implements AuthoritiesExtractor {
@Override
public Collection<GrantedAuthority> getAuthorities(XsuaaToken token) {
String appId = "";
if(token.getClientId().startsWith("sb-")) {
appId = token.getClientId().replaceFirst("sb-", "");
}
AuthoritiesExtractor authoritiesExtractor = new …
```
=> SECAUTH-1483

spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/extractor/BasicCredentialExtractorTest.java, spring-xsuaa-it/src/test/java/com/sap/cloud/security/xsuaa/extractor/TokenBrokerTestConfiguration.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/extractor/TokenBrokerResolver.java
fixes #705 
relates to https://github.com/SAP/cloud-security-xsuaa-integration/pull/562
=> Fix TokenBrokerResolver: use header creds in case of CLIENT_CREDENTIALS

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfiguration.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/DummyXsuaaServiceConfiguration.java
To avoid confusion when exception `java.lang.UnsupportedOperationException: getProperty method` is thrown for custom `XsuaaServiceConfiguration` implementations where the default `OAuth2ServiceConfiguration.getClientIdentity()` is not overridden, provide default `getClientIdentity()` method in `XsuaaClientConfiguration` interface that will notify user to implement the method and won't use the default from `OAuth2ServiceConfiguration` interface that calls unsupported `getProperty()` method.
=> fix misuse of OAuth2ServiceConfiguration.getClientIdentity() in XsuaaServiceConfiguration

java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTest.java, java-security-test/src/test/java/com/sap/cloud/security/test/SecurityTestRuleTest.java, java-security/src/main/java/com/sap/cloud/security/adapter/xs/XSUserInfoAdapter.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidator.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefaultTest.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaDefaultEndpoints.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaDefaultEndpointsTest.java
fixes #707
Hi @liga-oz 
Alternatively we could provide a new constructor
````
XsuaaDefaultEndpoints(String baseUri, @Nullable String certUri)
````
Furthermore, we could set the default certUri by adding the  that `https://subdomain.authentication.cert.domain`
=> XsuaaDefaultEndpoints: provide another constructor to compensate the deprecated one

env/src/test/java/com/sap/cloud/security/json/DefaultJsonObjectTest.java
Currently identity service provides token issuer with special escape characters, like here:
```json
{
"iss": "https:\/\/aoxk2addh.accounts400.ondemand.com",
"azp": "49363701-0c40-4f12-bc3b-46d969c0ea5c",
...
}
```
This PR adds a test in order to make sure, that JSON Parser can handle this properly.
=> make sure that escape characters are handled with JSON parser

CHANGELOG.md, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaCredentials.java, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationCustom.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationCustomTest.java
fix issue when `@ConfigurationProperties` doesn't load private key due to attribute name mismatch. In configuration files X509 private key is with 'key' attribute name
rename privateKey -> key
https://jtrack.wdf.sap.corp/browse/NGPBUG-168786
=> fix 'key' attribute name mismatch

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenService.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceClientCredentialsTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServiceJwtBearerTokenTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/XsuaaOAuth2TokenServicePasswordTest.java
This PR fixes the issue of mutable HttpHeaders object being updated in cacheKey after the MDC header is added to the request. 
Improves test coverage and replace usage of deprecated retrieveAccessTokenViaClientCredentialsGrant method.
=> Hotfix cache miss issue

docs/HowToFetchToken.md
Most CURL do not support the `https://username:password@hostname` notation. Instead the parameter `-u` must be used. See also https://linux.die.net/man/1/curl on that.
=> Fix CURL user notation instead of "inline to URL"

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtSignatureValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtSignatureValidatorTest.java, java-security/src/test/resources/iasJsonWebTokenKeys.json, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyService.java
In case of single-tenant applications ``iss`` claim in oidc token claim matches the identity provider url (``OAuth2ServiceConfiguration.getUrl())``. In that case ``x-zone_uuid`` header is not required to request the ``jwks_uri`` endpoint to retrieve token keys.
=> Support oidc tokens from single tenant apps w/o zone_uuid claim

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefault.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServiceConfigurationDefaultTest.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/XsuaaServicePropertySourceFactoryTest.java
Supports also non relaxed-binding rules for non spring framework cases
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding
=> [Spring] Support relaxed-binding rules

spring-security/src/test/java/com/sap/cloud/security/spring/token/authentication/JwtDecoderBuilderTest.java
name should be `buildHybridWithConfigurations` as the configurations are set to the builder.
=> fix test method name

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCache.java, java-security/src/test/resources/simplelogger.properties, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyService.java
as of now, in case of validation error the decoded jwt token gets logged (debug mode) and the JwtSignatureValidator error itself. Also, in case service returns error or status code != 200, an error will be written.
Additionally, with that PR also these circumstances / details gets logged as well, mostly in DEBUG mode.
**1. jku url does not provide any keys:**
> [main] DEBUG com.sap.cloud.security.token.validation.validators.OAuth2TokenKeyServiceWithCache - Configured token key cache with cacheDuration=600 seconds, cacheSize=1000 and statisticsRecording=false
[main] ERROR com.sap.cloud.security.token.validation.validators.OAuth2TokenKeyServiceWithCache - Retrieved no token keys from https://myauth.com/jwks_uri for zone id 'zone_uuid'
[main] DEBUG …
=> add further logs in respect to key mismatches

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtSignatureValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/OAuth2TokenKeyServiceWithCacheTest.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/XsuaaJwtSignatureValidatorTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyServiceTest.java
- Only identity service requires `x-zone_uuid` header for token keys retrieval
- in case of signature mismatch the result should expose the signature of the encoded JWT token
see also https://itsm.services.sap/now/workspace/agent/record/sn_customerservice_case/9f5bfe821bf9859862751f8f8b4bcbd1
=> JwtSignatureValidator improvements

env/pom.xml, java-api/pom.xml, java-security-test/pom.xml, java-security/pom.xml, pom.xml, spring-security-compatibility/src/main/java/com/sap/cloud/security/comp/XsuaaTokenComp.java, spring-security/pom.xml, spring-xsuaa-it/pom.xml, spring-xsuaa/pom.xml, token-client/pom.xml
closes #851 
follows recommendation from [here](https://spotbugs.readthedocs.io/en/stable/migration.html#guide-for-migration-from-findbugs-3-0-to-spotbugs-3-1)
[all]
- Dependency on spotbugs-annotations should be optional <br>
[spring-xsuaa]
- Dependency on javax.annotation-api should be optional
=> Dependency on spotbugs-annotations should be optional #851

etc/suppression.xml
Suppresses https://tanzu.vmware.com/security/cve-2022-22978
Unfortunately all the latest spring core versions were flagged by the vulnerability [CVE-2016-100002](https://nvd.nist.gov/vuln/detail/CVE-2016-1000027#vulnConfigurationsArea).
No fix as of now https://github.com/spring-projects/spring-framework/issues/24434#issuecomment-1132113566, but seems to be false positive.
As we don't use any of the [^HttpInvoker* classes](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#remoting-httpinvoker) from spring framework in our project, I think it's a false positive in our case and until spring 6.0.0 is out we can suppress it in owasp.dependency-check
=> add dependency-check suppression for CVE-2016-1000027

etc/suppression.xml
spring-boot-starter-security-2.7.0.jar is flagged as vulnerable, but seems to be false positive as I cannot find any reference where spring-security 5.7.x (which is used in project) would be vulnerable 
References:
https://spring.io/blog/2022/05/15/spring-security-5-7-0-5-6-4-5-5-7-released-fixes-cve-2022-22978-cve-2022-22976
https://nvd.nist.gov/vuln/detail/CVE-2022-22978
=> suppress CVE-2022-22978 

CHANGELOG.md, token-client/src/main/java/com/sap/cloud/security/xsuaa/util/UriUtil.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/util/UriUtilTest.java
fixes #943
In cases when uri does not contain http/s schema URI instance's `host` class member would be `null` which would lead to NPE thrown in `UriUtil.replaceSubdomain()` method.
=> Bug fix - NPE in UriUtil.replaceSubdomain()

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoderTest.java
- As a workaround for cases when xsuaa service configuration `verificationkey` attribute is malformed and throws `IllegalArgumentException` when decoding RSA public key, `XsuaaJwtDecoder` will catch `IllegalArgumentException` to avoid 500 error to be thrown by it. 
>RC of such malformed `verificationkey` remains unclear as the affected user could not provide service configuration details, therefore this is a workaround not an actual fix
- introduce stricter rule for fallback verificationkey validation
=> Workaround for malformed verificationkey in xsuaa configuration

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/httpclient/DefaultSpringHttpClientFactory.java
Fixes supported certificate protocol version mismatch with cf routing in spring-xsuaa module. Version 1.3 is not yet supported.
=> use TLS v1.2 for DefaultSpringHttpClientFactory

env/src/main/java/com/sap/cloud/security/config/ServiceBindingEnvironment.java, env/src/test/java/com/sap/cloud/security/config/ServiceBindingEnvironmentTest.java, env/src/test/resources/vcapXsuaaServiceMultipleApplicationPlanBindings.json, java-security/README.md
I changed ServiceBindingEnvironment to store service configurations as list instead of mapped by service plan.
In order to not break the existing public API for getting service configurations as a Map, I added ServiceBindingEnvironment#getServiceConfigurationsAsList as an alternative that returns all configurations
=> Restore support for multiple XSUAA Application Plan service bindings

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2ServiceException.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOidcConfigurationServiceTest.java
Expose the `httpStatusCode` field from `OAuth2ServiceException`.
It has been like this before, but the method had been removed in #1179.
If there is no reason not to expose it to the caller, we would like to have it back as our current code is relying on it for error handling.
=> expose http status code in OAuth2ServiceException

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2ServiceException.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyService.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/util/HttpClientTestFactory.java
Fixes problem, when `app_tid` is not present in token and sending only `x-client_id` header returns 400 from IAS.
`x-client_id` and `x-app_tid` headers have to be used together or not at all.
=> Add x-app_tid and x-client_id headers only when both are availabe

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2ServiceException.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyService.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenKeyServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/client/SpringOAuth2TokenKeyServiceTest.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/util/HttpClientTestFactory.java
Fixes problem, when app_tid is not present in token and sending only x-client_id header returns 400 from IAS.
x-client_id and x-app_tid headers have to be used together or not at all.
=> Add x-app_tid and x-client_id headers only when both are available

spring-security/src/main/java/com/sap/cloud/security/spring/autoconfig/XsuaaTokenFlowAutoConfiguration.java
The HttpClient bean is created for the XsuaaTokenFlows bean. However if the XsuaaTokenFlows bean is not created at all, the HttpClient still is. With this change the HttpClient is bound to the same conditions as the XsuaaTokenFlows bean.
=> Only create HttpClient bean if required

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtAudienceValidator.java
Previously JwtAudienceValidator was very chatty logging the derived audiences per request at info level. This happens once per request and makes the info log rather verbose.
Reduce log level to debug
=> Reduce log level in which JwtAudienceValidator logs derived audiences

CHANGELOG.md, pom.xml
Fixes https://nvd.nist.gov/vuln/detail/CVE-2023-5072
=> Bump org.json.version from 20230618 to 20231013

spring-security/src/main/java/com/sap/cloud/security/spring/config/IdentityServicesPropertySourceFactory.java
During a debugging session, I stumbled over a lot of redundant calls to the `CFEnvironment` class originating from `IdentityServicesPropertySourceFactory`. Although not causing any external calls, still the performance may be degraded slightly due to this. 
It seems rather easy to prevent the unnecessary calls by introducing a local variable. IMO that also makes the code easier to read. The pattern may be applied both when determining XSUAA service instances and IAS service instances. I have adjusted both occurrences.
As this change is expected to be trivial (bugfix contribution only) and should be non-disruptive for any consumer, I don't expect any credit to be mentioned.
=> Minor Performance Improvement: Avoid Several Redundant Calls to Environment Layer During Bootstrapping

spring-security/src/main/java/com/sap/cloud/security/spring/autoconfig/XsuaaTokenFlowAutoConfiguration.java
On each application startup, a log message "If the performance for the token validation is degrading provide your own well configured HttpClientFactory implementation" is written to application (logger `com.sap.cloud.security.spring.autoconfig.XsuaaTokenFlowAutoConfiguration`) which is not really helpful and can only be overruled explicitly by the application. Shouldn't this information be rather part of documentation (Javadoc and/or product documentation)?
=> Decrease log level of trace about default HttpClientFactory usage

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/OAuth2TokenServiceConstants.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/JwtBearerTokenFlow.java, token-client/src/test/java/com/sap/cloud/security/xsuaa/tokenflows/JwtBearerTokenFlowTest.java
JwtBearerTokenFlow: add additional setter to request an opaque token response
=> Update JwtBearerTokenFlow via cherry-pick for the 2.X token-client version 

java-security-test/pom.xml, java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTest.java, java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTestRule.java, java-security-test/src/main/java/com/sap/cloud/security/test/api/ApplicationServerConfiguration.java, java-security-test/src/main/java/com/sap/cloud/security/test/extension/SecurityTestExtension.java, java-security-test/src/main/java/com/sap/cloud/security/test/jetty/JettyTokenAuthenticator.java, java-security-test/src/test/java/com/sap/cloud/security/test/SecurityTestRuleTest.java, pom.xml, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaResourceServerJwkAutoConfigurationTest.java, spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaTokenFlowAutoConfigurationTest.java
Fixes https://github.com/SAP/cloud-security-services-integration-library/issues/1368
=> Use Jetty 12 with EE9 with Spring Boot 3.2

token-client/src/main/java/com/sap/cloud/security/client/DefaultHttpClientFactory.java, token-client/src/test/java/com/sap/cloud/security/client/DefaultHttpClientFactoryTest.java
`HttpClient` caching in `DefaultHttpClientFactory` does not add any value to the way how it is used across the other library modules, where the created `httpClient` is stored as a field variable in the corresponding classes and reused from there. 
Moreover, as the service configuration is loaded once per app start, extending a cache with a cache key that include a clientid, a certificate thumbprint and implementing also a cache eviction logic would not have any impact on key rotation without app restart and therefore caching the http connections would not bring anything.
=> remove httpclient caching from DefaultHttpClientFactory

java-security/pom.xml, java-security/src/main/java/com/sap/cloud/security/servlet/HybridTokenFactory.java, java-security/src/test/java/com/sap/cloud/security/servlet/HybridTokenFactoryTest.java
In case of DwC setup, there is no need to have an xsuaa service bound to the cloud foundry application. Token is validated in the jupiter component. Therefore, the WARN log should be written a single time time, and not every time the token gets created via `HybridTokenFactory`.
With that change the log messages looks as following (spring-security-hybrid-usage sample - TestControllerTest.sayHello()):
````
2024-01-02 16:03:14.873  WARN 19633 --- [           main] c.s.c.s.servlet.HybridTokenFactory       : There is no xsuaa service configuration with 'xsappname' property: no local scope check possible.
2024-01-02 16:03:36.415  INFO 19633 --- [           main] c.s.c.s.t.v.v.XsuaaJwtSignatureValidator : Loaded custom JKU factory
2024-01-02 16:03:56.008  INFO 19633 --- [           main] …
```
=> Support DwC - Avoid superflous WARN log messages

java-security-test/pom.xml, java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTest.java, java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTestRule.java, java-security-test/src/main/java/com/sap/cloud/security/test/api/ApplicationServerConfiguration.java, java-security-test/src/main/java/com/sap/cloud/security/test/extension/SecurityTestExtension.java, java-security-test/src/main/java/com/sap/cloud/security/test/jetty/JettyTokenAuthenticator.java, java-security-test/src/test/java/com/sap/cloud/security/test/SecurityTestRuleTest.java, pom.xml
=> Use jetty-ee10 instead of jetty-ee9

java-api/src/main/java/com/sap/cloud/security/config/CredentialType.java, java-api/src/test/java/com/sap/cloud/security/config/CredentialTypeTest.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/XsuaaDefaultEndpoints.java
This PR recognizes the credential types of IAS service bindings in the enum.
=> feat: Add IAS Credential Types

java-security-test/src/main/java/com/sap/cloud/security/test/SecurityTest.java, samples/java-security-usage-ias/pom.xml, samples/java-security-usage/pom.xml
In the sample libraries that used the @WebServlet annotation the tests didn't work. 
I made changes in the java-security-test library so that the base resource path of WebAppContext is now set dynamically based on the existence of a web.xml file.
=> Fix for usage of WebServlet annotation in java-security-test

java-security-test/src/main/java/com/sap/cloud/security/test/JwtGenerator.java, spring-security/Migration_SpringXsuaaProjects.md, spring-security/src/main/java/com/sap/cloud/security/spring/token/authentication/ReactiveHybridJwtDecoder.java, spring-security/src/test/java/com/sap/cloud/security/spring/token/authentication/ReactiveHybridJwtDecoderTest.java
IAT Claim (IssuedAt Claim) in XSUAA Token is numeric but was tried to read as a String. Fixes #1490
=> Fix for IAT Claim in ReactiveHybridJwtDecoder

CHANGELOG.md, pom.xml
Hello colleagues,
There is a Spring Framework security vulnerability [(BDSA-2024-1160)](https://sap.blackducksoftware.com/api/vulnerabilities/BDSA-2024-1160/overview)  on version `5.3.33`.
I updated `spring-core` to `5.3.34`
Is is possible to have a timeline for the release of `2.17.5` so we can plan our next release of the SAP Cloud SDK?
=> Update spring-core to 5.3.34

spring-security/src/main/java/com/sap/cloud/security/spring/autoconfig/SecurityContextAutoConfiguration.java, spring-security/src/test/java/com/sap/cloud/security/spring/autoconfig/SecurityContextAutoConfigurationTest.java
The library now registers a security context strategy by default. In CAP Java we ran into situations where this registration happened too late. The effect of this was, that SecurityConfigs used an obsolete SecurityContextStrategy (which stored by Spring Security as a member variable in the SecurityConfig) and the library set a new strategy in the static holder class. As the SecurityConfigs stored the authentication objects in the obsolete strategy, CAP wasn't able anymore to get the current authentication from the static holder class.
This PR tries to avoid this situation, by ensuring that the auto-configuration has a high precedence and is run early in the application initialization. Additional this PR avoids reflection usage to set the strategy, as reflection is not really required.
=> Improve the custom SecurityContext Strategy registration

token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java
in some cases, e.g. clientProtocolException, the message is empty, thus you don't know what's the issue
=> print whole exception of unexpected error

spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoderBuilder.java
spring-security has added a new x5t certificate thumbprint validator to the list of default validators:
https://github.com/spring-projects/spring-security/commit/644cfa9f875409d2b2bf01cd791d1a906e44c500#diff-a4724ab787f6f0344a9ab4d3d8f1ce9b0cd16f0b24a51d497b3290b41ed43a04R70-R73
This new validator is automatically getting used in the XsuaaJwtDecoder of the spring-xsuaa module of this lib once consumers update to a newer spring-security version.
This validator does not work for typical usage scenarios of this lib without further configuration because it expects a client certificate in the request. As TLS termination is done earlier by BTP and the certificate is instead forwarded in a header that is not used by the new validator, it will always fail to find a certificate for the validation. …
=> Remove new X5tCertificateThumbprintValidator from spring-xsuaa module

samples/sap-java-buildpack-api-usage/README.md, samples/sap-java-buildpack-api-usage/manifest.yml
With SAP Java Buildpack 2 supporting Tomcat 10, the sap-java-buildpack-api-usage sample is fully functional again. This change updates the manifest and removes the hint to the community buildpack from the README file.
=> Update sap-java-buildpack-api-usage to use 'sap_java_buildpack_jakarta'

token-client/src/main/java/com/sap/cloud/security/mtls/SSLContextFactory.java
[In our project](https://github.com/SAP/cloud-sdk-java) we noticed Windows users unable to run certain tests.
In many default installations of Git, the line-ending CRLF (`\r\n`) will be used when checking out text based files.
We found exceptions like the following (for `3.5.3`):
```
java.lang.IllegalArgumentException: Illegal base64 character d
at java.base/java.util.Base64$Decoder.decode0(Base64.java:852)
at java.base/java.util.Base64$Decoder.decode(Base64.java:570)
at java.base/java.util.Base64$Decoder.decode(Base64.java:593)
at com.sap.cloud.security.mtls.SSLContextFactory.getPrivateKey(SSLContextFactory.java:157)
at com.sap.cloud.security.mtls.SSLContextFactory.createKeyStore(SSLContextFactory.java:144)
at com.sap.cloud.sdk.cloudplatform.connectivity.BtpServicePropertySuppliers$Identi …
```
=> When parsing PEM files, consider CRLF (in addition to LF)

pom.xml
due to dependency issues with jetty-server referencing an incompatible jetty-util we revert the latest version update for now
=> revert jetty to 12.0.13

pom.xml
Dependency check is done by dependabot already and does not need to be done in the build. Furthermore, the build was unstable because of connection issues while downloading vulnerability data from NVD. Instead of investing into stabilizing the NVD based dependency check (e.g. by caching the NVD data), the decision was to replace it with a dependabot only approach.
As a consequence, during the release of a new library version, we need to double check for any waiting dependabot PRs that might fix a known vulnerability.
=> Remove dependency-check-maven plugin from build

java-security/src/main/java/com/sap/cloud/security/x509/X509Certificate.java, java-security/src/test/java/com/sap/cloud/security/x509/XfccCertificateTest.java
If parsing the x-forwarded-client-cert header as PEM fails, if possible the header is parsed based on the specification at: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert
=> Adding support for envoy x-forwarded-client-cert header format

pom.xml, spring-security/src/main/java/com/sap/cloud/security/spring/token/authentication/ReactiveHybridJwtDecoder.java
This PR brings two changes:
1. fix for reactive token validation error handling
2. downgrade of wiremock-standalone (to mitigate test issues)
=> Reactor fix and wiremock downgrade

env/src/main/java/com/sap/cloud/security/config/OAuth2ServiceConfigurationBuilder.java, env/src/test/java/com/sap/cloud/security/config/OAuth2ServiceConfigurationBuilderTest.java
A recent fix of the oauth configuration builder based on Map.copy for copying the properties of an configuration object broke consumers having null values (or keys) in the properties map of the configuration.
This change swaps tha call to Map.copy() with calling the constructor of HashMap which supports null. Same is done for copying the list of domains.
Fixes #1743
=> fix null value (and key) support in configuration builder

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/SapIdJwtSignatureValidator.java, java-security/src/main/java/com/sap/cloud/security/token/validation/validators/XsuaaJwtSignatureValidator.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOidcConfigurationService.java
Do not log an error during token key retrieval when a fallback is available.
Also: Improve error handling for OIDC discovery URL construction.
Bug: NGPBUG-429025
=> NGPBUG-429025 fix error logging during token key retrieval

env/src/main/java/com/sap/cloud/security/json/DefaultJsonObject.java, env/src/test/java/com/sap/cloud/security/json/DefaultJsonObjectTest.java, java-security/src/main/java/com/sap/cloud/security/token/AbstractToken.java
If token claims are retrieved via getClaimAsString(), then values of non-string type will now be converted using Object::toString().
=> NGPBUG-432478 auto-convert token claims to string

spring-security/src/main/java/com/sap/cloud/security/spring/autoconfig/XsuaaTokenFlowAutoConfiguration.java, token-client/src/main/java/com/sap/cloud/security/xsuaa/client/DefaultOAuth2TokenService.java
The DefaultOAuth2TokenService is used for Jakarta and Spring but the Retry feature was always configured with the non-Spring configuration.
=> SCICAS-3386 Fix spring retry configuration for token service

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/SapIdJwtSignatureValidator.java, java-security/src/test/java/com/sap/cloud/security/token/validation/validators/SapIdJwtSignatureValidatorTest.java
The old message was misleading since it is not the proof token that is missing in this case but the client certificate.
=> Improve error message when client certificate is missing

pom.xml, spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/XsuaaJwtDecoder.java
Bumping spring security version and fixing verification key fallback to no longer depend on exception messages.
=> Bump spring.security.version from 6.4.5 to 6.5.0

java-security/src/main/java/com/sap/cloud/security/token/validation/validators/XsuaaJwtSignatureValidator.java
To reduce log spamming in the legacy XSA case, we recently started to skip the logging of errors during token key retrieval. The error then was only logged if there was no verification key available for the fallback.
However, there are non-legacy cases, where a verification key is available. In these cases the new logic swallowed the error log. To improve the situation, we now only skip the error log if we are in the legacy mode.
=> SCICAS-3575 Improve logging before token key retrieval fallback

java-security-test/pom.xml, pom.xml
This includes the removal of a duplicate dependency to a depreceated location of the server module.
=> Update jetty dependency to 12.0.27
